adjust-ci
thoth-station/graph-metrics-exporter pull request #4
Opened 2021-06-17 08:32 UTC by pacospace

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Related-To: https://github.com/thoth-station/metrics-exporter/issues/704

2021-06-17 08:32 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **goern** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @goern` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fgraph-metrics-exporter).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/graph-metrics-exporter/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2021-06-17 20:24 UTC, harshad16 requested changes
just some minor required changes.

2021-06-17 20:24 UTC, harshad16 commented on .prow.yaml
> +              cpu: "2"
```suggestion
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "200m"
```

2021-06-17 20:24 UTC, harshad16 commented on .prow.yaml
> +              cpu: "200m"
```suggestion
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "200m"
```

2021-06-18 06:51 UTC, sesheta commented
@pacospace: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/mypy | 18ac5133b266db47412dd6737a2cb0dc6da0130c | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_graph-metrics-exporter/4/thoth-mypy-py38/1405779963352715264) | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=graph-metrics-exporter&pr=4). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Apacospace). Please help us and [open an issue](https://github.com/thoth-station/graph-metrics-exporter/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-18 07:27 UTC, sesheta commented
@pacospace: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/mypy | 386042de66d9059607f9eeca3c372900f1532c0a | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_graph-metrics-exporter/4/thoth-mypy-py38/1405789067928408064) | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=graph-metrics-exporter&pr=4). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Apacospace). Please help us and [open an issue](https://github.com/thoth-station/graph-metrics-exporter/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-18 07:28 UTC, pacospace commented
> @pacospace: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> aicoe-ci/prow/mypy	[386042d](https://github.com/thoth-station/graph-metrics-exporter/commit/386042de66d9059607f9eeca3c372900f1532c0a)	[link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_graph-metrics-exporter/4/thoth-mypy-py38/1405789067928408064)	`/test thoth-mypy-py38`
> [Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=graph-metrics-exporter&pr=4). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Apacospace). Please help us and [open an issue](https://github.com/thoth-station/graph-metrics-exporter/issues?q=is:issue+is:open) when you hit one in your PR.

Is this error `Failed to find Pipfile.lock, poetry.lock or requirements.txt in the current directory or any of its parent: /home/prow/go/src/github.com/thoth-station/graph-metrics-exporter` expected from mypy check @harshad16 ?

2021-06-18 07:34 UTC, fridex commented
> > @pacospace: The following test **failed**, say `/retest` to rerun all failed tests:
> > Test name	Commit	Details	Rerun command
> > aicoe-ci/prow/mypy	[386042d](https://github.com/thoth-station/graph-metrics-exporter/commit/386042de66d9059607f9eeca3c372900f1532c0a)	[link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_graph-metrics-exporter/4/thoth-mypy-py38/1405789067928408064)	`/test thoth-mypy-py38`
> > [Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=graph-metrics-exporter&pr=4). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Apacospace). Please help us and [open an issue](https://github.com/thoth-station/graph-metrics-exporter/issues?q=is:issue+is:open) when you hit one in your PR.
> 
> Is this error `Failed to find Pipfile.lock, poetry.lock or requirements.txt in the current directory or any of its parent: /home/prow/go/src/github.com/thoth-station/graph-metrics-exporter` expected from mypy check @harshad16 ?

I would say so. mypy can expect stub files being present thus it installs requirements. BTW that's also the reason why we do not want to have requirements that are not used in sources stated in Pipfile/Pipfile.lock - they make the testsuite slow and harder to potentionally debug any interference between versions (https://github.com/thoth-station/graph-metrics-exporter/pull/3#discussion_r653456916)

2021-06-18 07:38 UTC, pacospace commented
> > > @pacospace: The following test **failed**, say `/retest` to rerun all failed tests:
> > > Test name	Commit	Details	Rerun command
> > > aicoe-ci/prow/mypy	[386042d](https://github.com/thoth-station/graph-metrics-exporter/commit/386042de66d9059607f9eeca3c372900f1532c0a)	[link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_graph-metrics-exporter/4/thoth-mypy-py38/1405789067928408064)	`/test thoth-mypy-py38`
> > > [Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=graph-metrics-exporter&pr=4). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Apacospace). Please help us and [open an issue](https://github.com/thoth-station/graph-metrics-exporter/issues?q=is:issue+is:open) when you hit one in your PR.
> > 
> > 
> > Is this error `Failed to find Pipfile.lock, poetry.lock or requirements.txt in the current directory or any of its parent: /home/prow/go/src/github.com/thoth-station/graph-metrics-exporter` expected from mypy check @harshad16 ?
> 
> I would say so. mypy can expect stub files being present thus it installs requirements. BTW that's also the reason why we do not want to have requirements that are not used in sources stated in Pipfile/Pipfile.lock - they make the testsuite slow and harder to potentionally debug any interference between versions ([#3 (comment)](https://github.com/thoth-station/graph-metrics-exporter/pull/3#discussion_r653456916))

Thanks @fridex! Then we need to merge the other PR to have Pipfile

2021-06-18 08:56 UTC, pacospace commented
/cc @fridex

2021-06-18 09:00 UTC, sesheta commented
@pacospace: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/mypy | 154e891239305c533b93b8390a1dbad556b75ef7 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_graph-metrics-exporter/4/thoth-mypy-py38/1405811330916552704) | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=graph-metrics-exporter&pr=4). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Apacospace). Please help us and [open an issue](https://github.com/thoth-station/graph-metrics-exporter/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-18 09:02 UTC, fridex approved these changes
You can use `git pull --rebase` to avoid unnecessary merge commits in the git history. Also, having one PR per feature can make the git history clean and more maintainable - this will be helpful for future debugging.

thanks 👍🏻

2021-06-18 09:03 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/graph-metrics-exporter/pull/4#pullrequestreview-687192132" title="Approved">fridex</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fgraph-metrics-exporter).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/graph-metrics-exporter/blob/master/OWNERS)~~ [fridex]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-06-18 09:31 UTC, merged